CODE_FTXFutures = ''
LEVERAGE_FTXFutures = '20'
DEPO_FTXFutures = '0'
PART1_FTXFutures = '0'
PART2_FTXFutures = '0'
PART3_FTXFutures = '0'
PART4_FTXFutures = '0'
PART5_FTXFutures = '0'

CODE_BinanceFutures = ''
LEVERAGE_BinanceFutures = '1'
DEPO_BinanceFutures = '0'
PART1_BinanceFutures = '0'
PART2_BinanceFutures = '0'
PART3_BinanceFutures = '0'
PART4_BinanceFutures = '0'
PART5_BinanceFutures = '0'

CODE_FTXSpot = ''
LEVERAGE_FTXSpot = '1'
DEPO_FTXSpot = '0'
CURRENCY_FTXSpot = 'USD'
PART1_FTXSpot = '0'
PART2_FTXSpot = '0'
PART3_FTXSpot = '0'
PART4_FTXSpot = '0'
PART5_FTXSpot = '0'

AMOUNTS_CAN_BE_EDITED = ''
CSCALP_PATH = 'C:\Program Files (x86)\FSR Launcher'